### ISSUE TITLE
Extend articles endpoint with data required for Open Graph Twitter Cards support

### ISSUE THREAD

**Issue by taleldayekh** [taleldayekh/talel.io-backend#231]
### Description

The talel.io frontend should make use of Open Graph and Twitter Cards. The following tags are expected in the frontend:

- `og:title`/`twitter:title`: The title of an article.
- `og:type`/`twitter:card`: The type of the object being shared, in this case `article`.
- `og:image`/`twitter:image`: The URL to an image representing the article.
- `og:image:alt`/`twitter:image:alt`: A description of what is in the image representing the article.
- `og:description`/`twitter:description`: A brief description of the article being shared.
- `og:url`: The URL of the article (is there a Twitter variant for this?).

Most of these tags can be generated in the frontend from already existing API data except the `description`. The articles endpoint should therefore be extended to include `meta_description` but also `url`.

### Todo

- [x] Extend article model with description and url.
- [x] Update db with fields for description and url.
- [x] Add functionality for generating the url (need to consider the slug).
- [x] Include description and url in the create article use case.
- [x] Update endpoint to require description in request body.
- [x] Write tests.
- [x] Update API docs, also needs to be updated with past `featured_image` undocumented changes.
